const state=JSON.parse(localStorage.getItem('jeeOS')||'null')||{tasks:[],plans:[],tests:[],subjects:{Physics:0,Chemistry:0,Mathematics:0},notes:'',theme:'dark'};
const save=()=>localStorage.setItem('jeeOS',JSON.stringify(state));
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function renderTasks(){const box=$('#todayTasks');box.innerHTML=state.tasks.length?state.tasks.map((t,i)=>`<label class="task ${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} data-task="${i}"><span>${escapeHtml(t.text)}</span></label>`).join(''):'<div class="muted">No tasks yet. Add your first study target.</div>';$$('[data-task]').forEach(x=>x.onchange=()=>{state.tasks[+x.dataset.task].done=x.checked;save();render();});$('#taskCount').textContent=`${state.tasks.filter(t=>t.done).length}/${state.tasks.length}`;}
function renderPlans(){$('#planList').innerHTML=state.plans.length?state.plans.map(p=>`<div class="task"><span><b>${escapeHtml(p.title)}</b> · ${p.subject}</span><small class="muted">${p.minutes} min</small></div>`).join(''):'<div class="muted">No sessions scheduled.</div>';$('#focusTime').textContent=state.plans.reduce((a,p)=>a+Number(p.minutes),0)+' min';}
function renderSubjects(){const data=[['Physics',state.subjects.Physics],['Chemistry',state.subjects.Chemistry],['Mathematics',state.subjects.Mathematics]];$('#subjectCards').innerHTML=data.map(([s,p])=>`<div class="subject-card"><h3>${s}</h3><div class="bar"><i style="width:${p}%"></i></div><div class="subject-meta"><span>${p}% complete</span><input type="range" min="0" max="100" value="${p}" data-subject="${s}"></div></div>`).join('');$('#subjectMini').innerHTML=data.map(([s,p])=>`<div style="margin:14px 0"><div class="subject-meta"><span>${s}</span><span>${p}%</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`).join('');$$('[data-subject]').forEach(x=>x.oninput=()=>{state.subjects[x.dataset.subject]=+x.value;save();render();});const avg=Math.round(data.reduce((a,x)=>a+x[1],0)/3);$('#overallProgress').textContent=avg+'%';}
function renderTests(){$('#testList').innerHTML=state.tests.length?state.tests.slice().reverse().map(t=>`<div class="test-row"><span>${escapeHtml(t.name)}</span><b>${t.score}%</b></div>`).join(''):'<div class="muted" style="padding-top:18px">Record your first test to start analytics.</div>';$('#testCount').textContent=state.tests.length;}
function renderNotes(){$('#notes').value=state.notes;}
function render(){renderTasks();renderPlans();renderSubjects();renderTests();renderNotes();document.body.classList.toggle('light',state.theme==='light');}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function showView(name){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#view-'+name).classList.add('active-view');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const titles={dashboard:'Good study session.',planner:'Plan your next win.',subjects:'Track your PCM progress.',tests:'Turn mistakes into marks.',revision:'Your memory system.',notes:'Keep your learning in one place.'};$('#pageTitle').textContent=titles[name]||'JEE Life Time';window.scrollTo({top:0,behavior:'smooth'});}
$('#nav').onclick=e=>{const b=e.target.closest('.nav-item');if(b)showView(b.dataset.view)};$$('[data-view-link]').forEach(b=>b.onclick=()=>showView(b.dataset.viewLink));
$('#addTask').onclick=()=>{const v=$('#taskInput').value.trim();if(v){state.tasks.push({text:v,done:false});$('#taskInput').value='';save();render();}};
$('#taskInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#addTask').click()});
$('#addPlan').onclick=()=>{const title=$('#planTitle').value.trim();if(title){state.plans.push({title,subject:$('#planSubject').value,minutes:$('#planMinutes').value});$('#planTitle').value='';save();render();}};
$('#addTest').onclick=()=>{const name=$('#testName').value.trim();const score=Number($('#testScore').value);if(name&&score>=0){state.tests.push({name,score});$('#testName').value='';$('#testScore').value='';save();render();}};
$('#saveNotes').onclick=()=>{state.notes=$('#notes').value;save();$('#saveStatus').textContent='Saved just now';setTimeout(()=>$('#saveStatus').textContent='Saved locally',1500)};
$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();render()};
render();
